"""Generate predictions from a persisted V2 model without retraining."""

import argparse
import json
from pathlib import Path
import sys

import pandas as pd


PROJECT_ROOT = Path(__file__).resolve().parents[1]
SRC_DIR = PROJECT_ROOT / "src"
if str(SRC_DIR) not in sys.path:
    sys.path.insert(0, str(SRC_DIR))

from credit_risk.config import FEATURES
from credit_risk.predictors import PicklePredictor, validate_feature_frame


MODEL_CHOICES = (
    "logistic_regression",
    "random_forest",
    "xgboost",
    "lightgbm",
)

DEFAULT_INPUT = PROJECT_ROOT / "data" / "processed" / "X_test.csv"
DEFAULT_MODELS_DIR = PROJECT_ROOT / "artifacts" / "models"
DEFAULT_THRESHOLDS = (
    PROJECT_ROOT / "artifacts" / "metrics" / "model_thresholds.json"
)
DEFAULT_OUTPUT_DIR = PROJECT_ROOT / "artifacts" / "predictions"


def project_path(value: str) -> Path:
    """Resolve a CLI path relative to the project unless it is absolute."""
    path = Path(value)
    return path if path.is_absolute() else PROJECT_ROOT / path


def parse_args() -> argparse.Namespace:
    """Parse command-line options."""
    parser = argparse.ArgumentParser(
        description=(
            "Load one persisted V2 credit-risk model and generate "
            "probabilities and threshold-based predictions."
        )
    )
    parser.add_argument(
        "--model",
        required=True,
        choices=MODEL_CHOICES,
        help="Explicit persisted model identifier.",
    )
    parser.add_argument(
        "--input",
        default=str(DEFAULT_INPUT.relative_to(PROJECT_ROOT)),
        help="Feature CSV path, relative to the project by default.",
    )
    parser.add_argument(
        "--output",
        help=(
            "Prediction CSV path. Defaults to "
            "artifacts/predictions/<model>_predictions.csv."
        ),
    )
    parser.add_argument(
        "--thresholds",
        default=str(DEFAULT_THRESHOLDS.relative_to(PROJECT_ROOT)),
        help="Structured threshold artifact generated by train.py.",
    )
    return parser.parse_args()


def main() -> None:
    """Load features and a persisted model, then write predictions."""
    args = parse_args()
    input_path = project_path(args.input)
    thresholds_path = project_path(args.thresholds)
    model_path = DEFAULT_MODELS_DIR / f"{args.model}.pkl"
    output_path = (
        project_path(args.output)
        if args.output
        else DEFAULT_OUTPUT_DIR / f"{args.model}_predictions.csv"
    )

    for label, path in [
        ("input", input_path),
        ("model", model_path),
        ("thresholds", thresholds_path),
    ]:
        if not path.exists():
            raise FileNotFoundError(f"{label.capitalize()} not found: {path}")

    X = pd.read_csv(input_path)
    validate_feature_frame(X, FEATURES)

    threshold_artifact = json.loads(
        thresholds_path.read_text(encoding="utf-8")
    )
    model_threshold = threshold_artifact["models"].get(args.model)
    if model_threshold is None:
        raise KeyError(
            f"Threshold for model '{args.model}' not found in "
            f"{thresholds_path}."
        )

    threshold = float(model_threshold["threshold"])
    predictor = PicklePredictor(model_path)
    probability = predictor.predict_proba(X)

    predictions = pd.DataFrame(
        {
            "row_id": X.index,
            "model": args.model,
            "probability_default": probability,
            "threshold": threshold,
            "predicted_default": (probability >= threshold).astype(int),
        }
    )
    output_path.parent.mkdir(parents=True, exist_ok=True)
    predictions.to_csv(output_path, index=False)

    print("Prediction completed")
    print(f"  Model: {args.model}")
    print(f"  Model artifact: {model_path.relative_to(PROJECT_ROOT)}")
    print(f"  Input: {input_path}")
    print(f"  Rows: {len(predictions):,}")
    print(f"  Threshold: {threshold:.6f}")
    print(f"  Predicted default rate: {predictions['predicted_default'].mean():.4%}")
    print(f"  Output: {output_path}")


if __name__ == "__main__":
    main()
